//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDA.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_nhucaudinhduong
    {
        public int MaNhuCauDD { get; set; }
        public int Tuoi { get; set; }
        public Nullable<double> Kcalo { get; set; }
        public Nullable<double> Protein { get; set; }
        public Nullable<double> Calsi { get; set; }
        public Nullable<double> Sat { get; set; }
        public Nullable<double> VitaminA { get; set; }
        public Nullable<double> VitaminB1 { get; set; }
        public Nullable<double> VitaminB2 { get; set; }
        public Nullable<double> VitaminPP { get; set; }
        public Nullable<double> VitaminC { get; set; }
        public string GhiChu { get; set; }
    }
}
