//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDA.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_nhomtin
    {
        public int MaNhom { get; set; }
        public string TenNhom { get; set; }
        public string Slug { get; set; }
        public string MoTa { get; set; }
        public Nullable<int> DanhMucCha { get; set; }
        public Nullable<int> TinhTrang { get; set; }
        public Nullable<int> ThuTu { get; set; }
    }
}
