//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDA.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_hoadon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_hoadon()
        {
            this.tbl_hdchitiet = new HashSet<tbl_hdchitiet>();
        }
    
        public int MaPhieuHD { get; set; }
        public Nullable<int> MaThucDon { get; set; }
        public string SoPhieu { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string NguoiLap { get; set; }
        public Nullable<double> TongTien { get; set; }
        public string GhiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_hdchitiet> tbl_hdchitiet { get; set; }
        public virtual tbl_thucdon tbl_thucdon { get; set; }
    }
}
