//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDA.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_monan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_monan()
        {
            this.tbl_thanhphanmonan = new HashSet<tbl_thanhphanmonan>();
        }
    
        public int MaMonAn { get; set; }
        public Nullable<int> MaLoaiMonAn { get; set; }
        public string TenMonAn { get; set; }
        public Nullable<int> SoLuongNguoi { get; set; }
        public string ChuanBi { get; set; }
        public string CheBien { get; set; }
        public Nullable<double> TongProtidDV { get; set; }
        public Nullable<double> TongProtidTV { get; set; }
        public Nullable<double> TongLipidDV { get; set; }
        public Nullable<double> TongLipidTV { get; set; }
        public Nullable<double> TongGlucid { get; set; }
        public Nullable<double> TongCalo { get; set; }
        public Nullable<double> TongCanxi { get; set; }
        public Nullable<double> TongPhotpho { get; set; }
        public Nullable<double> TongSat { get; set; }
        public Nullable<double> TongVitaminA { get; set; }
        public Nullable<double> TongVitaminB1 { get; set; }
        public Nullable<double> TongVitaminB2 { get; set; }
        public Nullable<double> TongVitaminPP { get; set; }
        public Nullable<double> TongVitaminC { get; set; }
        public string GhiChu { get; set; }
    
        public virtual tbl_loaimonan tbl_loaimonan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_thanhphanmonan> tbl_thanhphanmonan { get; set; }
    }
}
