//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDA.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_hocsinh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_hocsinh()
        {
            this.tbl_hoantrahocphi = new HashSet<tbl_hoantrahocphi>();
            this.tbl_hocphi = new HashSet<tbl_hocphi>();
            this.tbl_hocsinhlop = new HashSet<tbl_hocsinhlop>();
        }
    
        public string MaHS { get; set; }
        public string HoTen { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string GioiTinh { get; set; }
        public string DanToc { get; set; }
        public string TonGiao { get; set; }
        public string QueQuan { get; set; }
        public string DiaChiTamTru { get; set; }
        public Nullable<int> MaUuTien { get; set; }
        public Nullable<System.DateTime> NgayVaoHoc { get; set; }
        public string DaNghiHoc { get; set; }
        public Nullable<System.DateTime> NgayNghiHoc { get; set; }
        public string HoTenCha { get; set; }
        public Nullable<System.DateTime> NgaySinhCha { get; set; }
        public string NgheNghiepCha { get; set; }
        public string HoTenMe { get; set; }
        public Nullable<System.DateTime> NgaySinhMe { get; set; }
        public string NgheNghiepMe { get; set; }
        public string DienThoaiLienHe { get; set; }
        public string EmailPhuHuynh { get; set; }
        public string HinhAnh { get; set; }
        public string TenThuongGoi { get; set; }
        public string TinhCach { get; set; }
        public string HoanThanhMN { get; set; }
        public string GhiChu { get; set; }
    
        public virtual tbl_doituonguutien tbl_doituonguutien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_hoantrahocphi> tbl_hoantrahocphi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_hocphi> tbl_hocphi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_hocsinhlop> tbl_hocsinhlop { get; set; }
    }
}
