//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDA.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_dmhocphi
    {
        public int MaDMHocPhi { get; set; }
        public Nullable<int> MaLoaiChiPhi { get; set; }
        public Nullable<int> SoTien { get; set; }
        public Nullable<System.DateTime> NgayApDung { get; set; }
        public string NamHoc { get; set; }
        public string LoaiApDung { get; set; }
        public string GhiChu { get; set; }
    }
}
