//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDA.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_tintuc
    {
        public int MaTin { get; set; }
        public string TieuDe { get; set; }
        public string NoiDung { get; set; }
        public string Slug { get; set; }
        public string Tags { get; set; }
        public string AnhDaiDien { get; set; }
        public string NguoiTao { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string NguoiSua { get; set; }
        public Nullable<System.DateTime> NgaySua { get; set; }
        public Nullable<int> LuotXem { get; set; }
        public Nullable<int> LuotXetDuyet { get; set; }
        public string MoTa { get; set; }
        public string TuKhoa { get; set; }
        public Nullable<int> NhomTin { get; set; }
        public string TinhTrang { get; set; }
        public Nullable<int> temp1 { get; set; }
        public Nullable<int> temp2 { get; set; }
        public string temp3 { get; set; }
        public string temp4 { get; set; }
    }
}
