//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDA.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_thucdon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_thucdon()
        {
            this.tbl_hoadon = new HashSet<tbl_hoadon>();
        }
    
        public int MaThucDon { get; set; }
        public string TenThucDon { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string NoiDung { get; set; }
        public string NguoiLap { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public string GhiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_hoadon> tbl_hoadon { get; set; }
        public virtual tbl_nhanvien tbl_nhanvien { get; set; }
    }
}
