//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDA.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_nhucaunangluong
    {
        public int MaNhuCauNL { get; set; }
        public string DoTuoi { get; set; }
        public Nullable<double> CaloCaNgay { get; set; }
        public Nullable<double> CaloTruong { get; set; }
        public Nullable<double> ProtidCaNgay { get; set; }
        public Nullable<double> ProtidTruong { get; set; }
        public Nullable<double> LipidCaNgay { get; set; }
        public Nullable<double> LipidTruong { get; set; }
        public Nullable<double> GlucidCaNgay { get; set; }
        public Nullable<double> GlucidTruong { get; set; }
        public string GhiChu { get; set; }
    }
}
