//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDA.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_hdchitiet
    {
        public int MaHDCT { get; set; }
        public Nullable<int> MaPhieuHoaDon { get; set; }
        public Nullable<int> MaThucPham { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public string DonViTinh { get; set; }
        public Nullable<double> SoLuong { get; set; }
        public Nullable<double> ThanhTien { get; set; }
        public string GhiChu { get; set; }
    
        public virtual tbl_hoadon tbl_hoadon { get; set; }
        public virtual tbl_thucpham tbl_thucpham { get; set; }
    }
}
