//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDA.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_hoantrahocphi
    {
        public int MaHoanTraHP { get; set; }
        public string MaHocSinh { get; set; }
        public Nullable<int> MaLop { get; set; }
        public string NamHoc { get; set; }
        public Nullable<int> TienHoanTra { get; set; }
        public string LyDoTra { get; set; }
        public string GhiChu { get; set; }
    
        public virtual tbl_hocsinh tbl_hocsinh { get; set; }
    }
}
