//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDA.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_thanhphanmonan
    {
        public int MaMonAnCT { get; set; }
        public Nullable<int> MaMonAn { get; set; }
        public Nullable<int> MaThucPham { get; set; }
        public Nullable<double> SoLuongGam { get; set; }
        public Nullable<double> ProtidDV { get; set; }
        public Nullable<double> ProtidTV { get; set; }
        public Nullable<double> LipidDV { get; set; }
        public Nullable<double> LipidTV { get; set; }
        public Nullable<double> Glucid { get; set; }
        public Nullable<double> Calo { get; set; }
        public Nullable<double> Canxi { get; set; }
        public Nullable<double> PhotPho { get; set; }
        public Nullable<double> Sat { get; set; }
        public Nullable<double> VitaminA { get; set; }
        public Nullable<double> VitaminB1 { get; set; }
        public Nullable<double> VitaminB2 { get; set; }
        public Nullable<double> VitaminPP { get; set; }
        public Nullable<double> VitaminC { get; set; }
        public string GhiChu { get; set; }
    
        public virtual tbl_monan tbl_monan { get; set; }
        public virtual tbl_thucpham tbl_thucpham { get; set; }
    }
}
