//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDA.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_hocphi
    {
        public string MaHocPhi { get; set; }
        public string TenHDHocPhi { get; set; }
        public string MaHocSinh { get; set; }
        public Nullable<int> Thang { get; set; }
        public string NamHoc { get; set; }
        public Nullable<int> TienMienGiam { get; set; }
        public Nullable<System.DateTime> NgayThu { get; set; }
        public string NguoiThu { get; set; }
        public Nullable<int> TongHocPhi { get; set; }
        public Nullable<int> DaThu { get; set; }
        public Nullable<int> ConNo { get; set; }
        public string LoaiHP { get; set; }
        public string GhiChu { get; set; }
    
        public virtual tbl_hocsinh tbl_hocsinh { get; set; }
        public virtual tbl_nhanvien tbl_nhanvien { get; set; }
    }
}
