//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDA.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_loaichiphi
    {
        public int LoaiChiPhi { get; set; }
        public string TenLoaiChiPhi { get; set; }
        public string LaHPKhoaChinh { get; set; }
        public string GhiChu { get; set; }
    }
}
